server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 5 # in second
  refreshable-duration: 120 # in second