server:
  port: 8081
spring:
  application:
    name: nyano
  datasource:
    url: "jdbc:mysql://localhost:3306/shopdevgo"
    username: root
    password: 12345

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true